### ISSUE TITLE
yarn create @waku/app

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku-examples#154]
Write a `@waku/create-app` tool (probably new repo) that pulls any existing example (can be a parameter) from the js-waku-examples repo to enable hackers to have a starting ground.

Note: Most likely need to also add a webserver for the `index.html` examples to make it easy to run locally (as done for rln with https://github.com/waku-org/js-waku-examples/pull/156)

## API

```
yarn create @waku/app
# create a repo and clone/copy one of the example. new default example
yarn start # starts webserver
```

OR
```
yarn create @waku/app --template rln-js
# create a repo and clone/copy the rln-js example
yarn start # starts webserver
```

## New Default Example

- uses filter + light-push
- similar to light-js: but no dial button, no subscribe filter
- index.html + index.js (ESM JS)
- uses web-chat/chat2 compatible logic (protobuf message + content topic)

## DoD

- [ ] All examples are npm repos with a `start` script (ie, some repos are only `index.html` file
  - [ ] may want to separate js in `index.js`, Jenkins would need to be updated
- [ ] new example that would be the default one
- [ ] yarn create script

**Comment by weboko** [comment]
In this message I will try to summarise my understanding of this issue and how I will approach it. 

What we want to provide to devs:
- a repo they can clone and run experiments;
- a npm package which they can `yarn create waku-app` or `npx create-waku-app`;

nb: Here I propose to use conventional `create-X-app` naming.

In order to achieve it I think `js-waku-examples should be reorganised so that all examples copied by `create-waku-app` will be located in the same place & we can support initiator of apps and templates in the same place.

As for the structure I'd like to use similar to the one you did in the `js-waku` so that we have a `packages` folder which will contain `create-waku-app` and possibly other packages, separately from it there will be `examples` folder.

**Comment by fryorcraken** [comment]
> In order to achieve it I think js-waku-examples should be reorganised so that all examples copied by create-waku-app will be located in the same place & we can support initiator of apps and templates in the same place.

Not sure I understand, all examples are already located in the same place (this repo).

> As for the structure I'd like to use similar to the one you did in the js-waku so that we have a packages folder which will contain create-waku-app and possibly other packages, separately from it there will be examples folder.

Oh, are you saying that the package for the create script + the code example should all be in the same repo. Sure why not.

**Comment by fryorcraken** [comment]
> As for the structure I'd like to use similar to the one you did in the js-waku so that we have a packages folder which will contain create-waku-app and possibly other packages, separately from it there will be examples folder.

What I noticed with yarn and npm monorepo is because there is one common node_modules folder at root, then if example a and b uses same dependency c, but c is not declared in b's package.json but is in a's then the CI doesn't pick up the issue until you copy b's code outside the monorepo.

**Comment by weboko** [comment]
Specific of `js-waku-examples` allows us to avoid having monorepo in traditional sense and we can just have a bunch of npm packages independent of each other.
We can have following structure:
- packages
    - create-waku-app
    - example-1
    - example-2
- ci stuff in the root

We don't really need to have package.json in the root of the repo for the examples and packages that might be inside.

**Comment by weboko** [comment]
Things to follow-up:
- [ ] better logging messages to show progress / error states;
- [ ] cover presence of yarn / offline mode / pnp and lock files - not exhaustive list;
- [ ] double check if `execSync` reliable enough;
- [ ] move examples in the repo to dedicated folder and remove usage of `wakuExamples` from `package.json`;
- [ ] update docs on the site to show that this app can be used;
- [ ] cover by some tests;
- [ ] check import ES modules;
- [ ] configure ci to support this package;
- [ ] add support similarly to `hardhat`, idea from @danisharora099

```
👷 Welcome to Hardhat v2.9.9 👷‍

? What do you want to do? …
❯ Create a JavaScript project
  Create a TypeScript project
  Create an empty hardhat.config.js
  Quit
```

**Comment by weboko** [comment]
- [ ] cover presence of yarn / offline mode / pnp and lock files - not exhaustive list; - now the `@waku/app` uses `npm` and while testing I did not find any issues with it
- [ ] better logging messages to show progress / error states; - for now I would leave it like that since the messages are quite informative

**Comment by weboko** [comment]
Slight updates to the `js.waku.guide` - [PR](https://github.com/waku-org/js.waku.guide/pull/66)

**Comment by fryorcraken** [comment]
```
▶ yarn create waku-app waku_app 
yarn create v1.22.19
warning package.json: No license field
warning ../../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "create-redwood-app > @redwoodjs/internal > @babel/plugin-transform-typescript@7.15.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "create-redwood-app > @redwoodjs/internal > @babel/register@7.15.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/typescript-react-apollo@3.0.0" has unmet peer dependency "graphql-tag@^2.0.0".
warning "create-redwood-app > @redwoodjs/internal > @babel/plugin-transform-typescript > @babel/helper-create-class-features-plugin@7.15.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "create-redwood-app > @redwoodjs/internal > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
[4/4] Building fresh packages...
success Installed "create-waku-app@0.1.0" with binaries:
      - create-waku-app
Initializing waku_app from web-chat template.
Installing npm packages.
Successfully installed npm dependencies.
Initiating git repository.
Successfully initialized git repo.
Done in 42.63s.
```

Some feedback @weboko 
- Can we reduce the number of warnings?
- Can we print more information to the user such as: what template was used, what are the next steps?

Or should we be using `@waku/create-app`?

```
▶ yarn create @waku/app waku_app
yarn create v1.22.19
warning ../package.json: No license field
warning ../../../package.json: No license field
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@waku%2fcreate-app: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/fryorcraken/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by weboko** [comment]
@fryorcraken, please, try to use `create-waku-app` again and share your feedback :) 
I updated version now and it should behave differently:
![image](https://user-images.githubusercontent.com/118575614/212147069-1825956d-bfe2-4502-8a7f-01ea2a35d891.png)

I would prefer using `@waku/create-app` but I cannot publish it under the scope of our organisation so if you can share access with me of publish yourself - would be good. For now we can continue with `create-waku-app`.

**Comment by fryorcraken** [comment]
@weboko can we add an issue in waku-org/waku.guide to document this? Cc @hackyguru to include in the hackathon guide (wdyt). Cc @alrevuelta / @danisharora099  for EthDenver workshop, this would be a great tool.

**Comment by fryorcraken** [comment]
@weboko is it possible to delete create-waku-app from npm? So that nobody gets confused?

**Comment by weboko** [comment]
Good point, removed the package
