### ISSUE TITLE
rln-js local development issues

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku-examples#155]
## Problem

MetaMask in Firefox and Chrome do not work when:

- directly opening the `rln-js/index.html` file from fs.
- using a local web server (tried with the WebStorm one) to serve the page

It works fine in Brave

## Proposed Solutions

1. Document the issue in README and possibly have a banner in index.html file when detecting inhospitable conditions
2. Investigate the issue, can't be the only dev with this issue.
3. See of a local NodeJS server somehow work better.

**Comment by fryorcraken** [comment]
Provided local web server with #156 

Opened discussions re Firefox/MetaMask issue:
- https://github.com/ethers-io/ethers.js/discussions/3526
- https://github.com/MetaMask/metamask-extension/discussions/16579

**Comment by danisharora099** [comment]
Unable to reproduce this for myself: I use Firefox Developer Edition + MetaMask

Though it's unlikely, I can follow up with regular LTS Firefox with MetaMask to see if it gives similar results.

**Comment by danisharora099** [comment]
Confirmed with Firefox + MetaMask also; works fine for me.

Using `http-serve` to serve.

**Comment by fryorcraken** [comment]
I guess you use MacOs @danisharora099 ? What about @weboko, what system do you use? I wonder if its a Linux only issue.

**Comment by weboko** [comment]
There is an issue if one tries to open `html` file directly without using any local web server - it happens because of the `ether` lib, probably fails to resolve URL's. When I use `serve` then all good. I am using Mac but same behaviour on Windows.

**Comment by fryorcraken** [comment]
Assumed that the issue was because a file was opened instead of using local web server
