### ISSUE TITLE
chore: move back to npm

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku-examples#164]
Now this repo uses `pnpm` as a package manager.
It is a good idea to move back to `npm` due to various reasons such as:
- the fact that other package managers do not provide enough gain;
- risk compatibility with whole ecosystem and getting additional quirks;
- major as I see it - this repo is a reference for developers and I would say that `npm` is a tool everyone knows;

What to look for:
- it is possible to see some errors in `angular` example;
- `web-chat` example uses a library that had problems with `npm` according to @fryorcraken;

What to do:
- [ ] try to apply `npm` as it is on the examples;
- [ ] get rid of the `lock` files in the repo;

**Comment by fryorcraken** [comment]
Regaring the web-chat, we should try to get read of the live ui library.
Ideally, we should just some simple handmade React components.

We can either do that ourselves as I believe we may have the skills in the team. Or we can follow-up with Comms Hubs Cc @amirhouieh who mentioned they would be keen to help us have a uniform styling across examples.
