### ISSUE TITLE
feat: js-rln: make the signature message editable

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku-examples#166]
This is a feature request for js-rln.

Make the signature message used as entropy to generate RLN credentials arbitrary/editable

**Comment by fryorcraken** [comment]
There was actually some discussions related to adding a password for RLN credentials generation https://discord.com/channels/864066763682218004/905333924476108800/1037521430008561756

I don't think the full message should be editable. This introduce too many risks of error.
Enabling an optional password would be better.

However, even an optional password seems risky. Are we saying that the zk credentials are more valuable than the user Ethereum's wallet?

Cc @s1fr0

**Comment by danisharora099** [comment]
> There was actually some discussions related to adding a password for RLN credentials generation https://discord.com/channels/864066763682218004/905333924476108800/1037521430008561756
> 
> I don't think the full message should be editable. This introduce too many risks of error. Enabling an optional password would be better.
> 
> However, even an optional password seems risky. Are we saying that the zk credentials are more valuable than the user Ethereum's wallet?
> 
> Cc @s1fr0

That makes sense. Happy to close this if looks good with @s1fr0 and @weboko.s

**Comment by fryorcraken** [comment]
Let's close until @s1fr0 provides new guidelines/RFC around usage of password in phrase to sign for seeding.
