### ISSUE TITLE
web-chat: remove explicit module declaration for dns-discovery

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku-examples#191]
ref: https://github.com/waku-org/js-waku-examples/pull/190, https://github.com/waku-org/js-waku/issues/1124

**Comment by fryorcraken** [comment]
Can you add a bit more details to this issue? I don't get it.

**Comment by weboko** [comment]
This task will require update to the never version of `dns-discovery` with a fix which in turn, potentially, can force us into updating packages to never version.

**Comment by weboko** [comment]
Took into work since had to upgrade packages for the example for https://github.com/waku-org/js-waku/issues/1353
