### ISSUE TITLE
noise-js and noise-rtc: use `@waku/*` packages instead of `js-waku`

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku-examples#205]
noise-js and noise-rtc examples currently install`js-waku` instead of `@waku/*` 

- [x] upgrade `@waku/core` to 0.0.10

**Comment by weboko** [comment]
I've been planning on updating it after completing this one https://github.com/waku-org/js-noise/pull/18
The problem with that is it fails because of some internal error with interfaces.

**Comment by weboko** [comment]
I left comment about it there - https://github.com/waku-org/js-noise/pull/18#issuecomment-1411297621

**Comment by fryorcraken** [comment]
I believe this is done. Do we just need to release `@waku/noise` to close this issue @weboko ?

**Comment by weboko** [comment]
Connected to https://github.com/waku-org/js-waku-examples/issues/220
