### ISSUE TITLE
[web-chat] Bootstrap peer display remains at 0

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku-examples#231]
Go to https://examples.waku.org/web-chat/

Check the bar:

> Bootstrap (DNS Discovery): 0, Peer exchange: 0. View console for more details.

despite being connected to a store peer and retrieving messages.

Cc @danisharora099

**Comment by weboko** [comment]
Fixed here https://github.com/waku-org/js-waku-examples/pull/230

Can you check if it works for you @fryorcraken ?

**Comment by fryorcraken** [comment]
Yes fixed, thx
