### ISSUE TITLE
bug(web-chat): message ordering is flaky

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku-examples#263]
The web-chat examples has been spotted to have weird ordering of messages retrieved from the store/filter protocols while being rendered.

TODO:
- [ ] investigate why it's happening
- [ ] open relevant issues, if required, in js-waku; else, open a PR is the examples repo

![image](https://github.com/waku-org/js-waku-examples/assets/35004822/bfa1e104-ea8d-4ab1-98c7-69260f6d872a)

![image](https://github.com/waku-org/js-waku-examples/assets/35004822/720950bd-459b-46c1-b469-5b6ff5c4bad9)

The messages need to be ordered correctly by time

**Comment by fryorcraken** [comment]
Pretty sure I fixed that.
