### ISSUE TITLE
Update name of js-waku-examples repo to 'examples'

### ISSUE THREAD

**Issue by chair28980** [waku-org/js-waku-examples#293]
Based on discussion from EcoDev monthly call and 2023 events retrospective, we should update the name of this repository to a more general name: `examples`.

## Tasks
- [ ] Update name of repo
- [ ] Identify broken links in https://docs.waku.org

**Comment by chair28980** [comment]
cc @fryorcraken @vpavlin

**Comment by fryorcraken** [comment]
Please check issues on this repo. We already have an issue to track split to labs vs examples

**Comment by fryorcraken** [comment]
Please add this proposal to https://github.com/waku-org/js-waku-examples/issues/275 and close this issue as dupe.
