### ISSUE TITLE
Examples: add tests

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku-examples#72]
non-regression tests are needed to ensure that the show case, deployed on `master` branch updates, still works.

Also, remove `WakuMock` once the tests are in place.

**Comment by fryorcraken** [comment]
Adding remove some agility to examples. As when a hacker play with them they may need to update/remove the tests.

Could do very basic tests:
- check components are rendered/usable
- Check no errors in logs

Best to ship first with the new react components.
Code readability is most important.

**Comment by weboko** [comment]
In https://github.com/waku-org/js-waku/pull/1542 this was partially addressed. 
Other things will be completed in https://github.com/waku-org/js-waku/issues/1597

I think at this point this issue can be closed.

@fryorcraken re-open if disagree
